/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polymorphism;


import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ebsuvilla
 */
public class ComputerMenu extends javax.swing.JFrame {

    /**
     * Creates new form ComputerMenu
     */
    public ComputerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnList = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnList.setBackground(new java.awt.Color(153, 153, 255));
        btnList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("computer frame");
        btnList.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 390, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(153, 204, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(255, 204, 255)));
        list.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        list.setForeground(new java.awt.Color(102, 102, 255));
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "COMPUTER", "INPUT DEVICES", "OUTPUT DEVICES", "SYSTEM UNIT", "PROCESSOR", "NETWORK", "INTERNET", "WWW", "ROUTER", "VIRUS", "COBOL", "INFORMATION AGES", "NUMBER SYSTEM", "WORD PROCESSORS", "COREL DRAW", "PAINT", "SPREAD SHEET PACKAGES", "INTERNET", "DATABASE MAGEMENT SYSTEM" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 370));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(102, 102, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polymorphism/images/setting-32x32-1214292.png"))); // NOI18N
        jButton2.setText("SETTINGS");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, 40));

        btnList.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 900, 420));

        home.setBackground(new java.awt.Color(153, 153, 255));
        home.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 11)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polymorphism/images/home.png"))); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        btnList.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polymorphism/images/29.png"))); // NOI18N
        btnList.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 90));

        getContentPane().add(btnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        // adding action for list items by Nelson
        
        int display  = list.getSelectedIndex();
        if (list.getSelectedIndex()==0){
            ImageIcon img = new ImageIcon("src/polymorphism/images/computer.png");
            JOptionPane.showMessageDialog(null, "Computer is an electronic devices that accepts input from any input devices, process it at a high speed and display it through output devices which can be stored for future use", "Introduction", JOptionPane.PLAIN_MESSAGE, img);
            
        }
        
        if (list.getSelectedIndex()==1){
            ImageIcon img = new ImageIcon("src/polymorphism/images/inputs.png");
            JOptionPane jop = new JOptionPane();
            jop.showMessageDialog(this, "input devices are the devices used to send signal to the computer system, examples of input devices are mouse, keyboard, microphone etc", "input devices", JOptionPane.PLAIN_MESSAGE, img);
            
            
        }
        if (list.getSelectedIndex() == 2){
            JOptionPane.showMessageDialog(null, "An output device is simply a device we use to get results of processed data from the\n"+ "computer system example of output devices are monitor, speaker, printer e.t.c");
        }
        if(list.getSelectedIndex()== 3){
            JOptionPane.showMessageDialog(null, "the system unit is the physical part of the computer system \n"+ "that contains other component like hard disk, mother board, power supply unit, DVD drive");
        }
        
        if(list.getSelectedIndex() == 4){
            ImageIcon img = new ImageIcon("src/polymorphism/images/processor.jpg");
            JOptionPane.showMessageDialog(null, "Microprocessor is a controlling unit of a micro-computer, \n"+"fabricated on a small chip capable of performing ALU (Arithmetic Logical Unit) \n"+"operations and communicating with the other devices connected to it.","prcesor", JOptionPane.PLAIN_MESSAGE,img);
            
        }
        if (list.getSelectedIndex() == 5){
            JOptionPane.showMessageDialog(null, "network is simply the connection that exist between two or more computer system with the aim of sharing resourcces");
        }

    }//GEN-LAST:event_listMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
      // creating button for hompage by Nelson
      Menu mn = new Menu();
      mn.setVisible(true);
      mn.pack();
      dispose();
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnList;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    // End of variables declaration//GEN-END:variables
}
